# 데이터셋 링크
- https://drive.google.com/file/d/15RN0lq7ouIXl5IXzMTAnCrogYPuH11fv/view?usp=sharing
- https://drive.google.com/file/d/1nZQHhBendwdhtNzXXiD9clOgXOTSdmMn/view?usp=sharing
- https://drive.google.com/file/d/10VKWGcPgREwf-l7vveegKtQf5XYqYlNA/view?usp=sharing


In [18]:
import numpy as np

## 1. MAE 와 RMSE 함수 구현하기
- 다음과 같이 실제 값과 , 모델이 예측한 값이 각각 100개가 있다.
- 실제값과 예측값 사이에 평균 오차를 구하는 함수 두개를 구현해보자.

In [19]:
np.random.seed(42)
target = np.random.randint(50, 91,100) # 정답값
pred = np.random.randint(40, 100,100) # 예측값
target , pred

(array([88, 78, 64, 57, 70, 88, 68, 72, 60, 60, 73, 85, 89, 73, 52, 71, 51,
        73, 79, 87, 51, 70, 82, 61, 71, 74, 76, 77, 65, 64, 52, 86, 56, 70,
        58, 88, 67, 53, 74, 63, 58, 75, 51, 69, 77, 56, 57, 84, 63, 66, 85,
        89, 53, 51, 55, 53, 78, 67, 75, 83, 59, 85, 63, 80, 64, 57, 63, 72,
        89, 70, 65, 67, 73, 75, 74, 90, 78, 64, 50, 74, 56, 58, 73, 50, 57,
        73, 60, 66, 57, 84, 84, 82, 54, 88, 90, 77, 56, 58, 57, 61]),
 array([73, 72, 87, 94, 62, 63, 76, 74, 83, 79, 61, 66, 74, 40, 74, 76, 86,
        53, 42, 40, 44, 65, 94, 53, 78, 66, 48, 54, 54, 65, 81, 99, 52, 90,
        71, 78, 88, 91, 71, 43, 69, 76, 62, 78, 84, 54, 82, 68, 75, 52, 71,
        46, 98, 90, 61, 67, 41, 81, 84, 96, 92, 45, 67, 67, 83, 83, 59, 69,
        50, 97, 94, 67, 64, 78, 72, 40, 96, 66, 96, 91, 52, 80, 42, 78, 45,
        47, 66, 48, 76, 72, 90, 81, 83, 63, 54, 98, 93, 71, 71, 63]))

### MAE(Mean Absolute Error)
- 실제 값과 예측 값의 차이를 절대값으로 변환해 평균
$$
MAE = \frac{1}{n}{\sum_{i=1}^{n}|y_i-\hat{y}_i|}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [28]:
def mae(target,pred):
    return abs(np.subtract(target, pred))
    
print(mae(target,pred))


[15  6 23 37  8 25  8  2 23 19 12 19 15 33 22  5 35 20 37 47  7  5 12  8
  7  8 28 23 11  1 29 13  4 20 13 10 21 38  3 20 11  1 11  9  7  2 25 16
 12 14 14 43 45 39  6 14 37 14  9 13 33 40  4 13 19 26  4  3 39 27 29  0
  9  3  2 50 18  2 46 17  4 22 31 28 12 26  6 18 19 12  6  1 29 25 36 21
 37 13 14  2]


### RMSE(Root Mean Squared Error)
- 실제 값과 예측 값의 차이를 제곱한 뒤 평균한 후에 루트

$$
RMSE = \sqrt{\frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [34]:
def rmse(target,pred):
    sum = np.square(np.subtract(target, pred))
    return np.sqrt((np.sum(sum)/len(sum)))

rmse(target, pred)

np.float64(21.829796151132516)

## 2.시그모이드 함수 구현하기
- S와 같은 형태로 미분 가능한 0~1 사이의 값을 반환한다.
- 이진 분류에 출력 함수로 사용된다.
$$
y = \frac{1}{1+e^{-x}}
$$

- x 변수에 있는 배열의 요소들을 시그모이드 함수에 넣어 0 ~ 1 사이 값들로 변경하시오.

In [25]:
np.random.seed(42)
x = np.random.randint(-10,10,10)
x

array([-4,  9,  4,  0, -3, -4,  8,  0,  0, -7])

```
아래 셀의 코드 작성하여 함수구현
```

In [32]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

sigmoid(x)

array([1.79862100e-02, 9.99876605e-01, 9.82013790e-01, 5.00000000e-01,
       4.74258732e-02, 1.79862100e-02, 9.99664650e-01, 5.00000000e-01,
       5.00000000e-01, 9.11051194e-04])

## 3.다음의 3행 2열형태의 배열에서 두개 열 위치를 바꾸시오.

In [33]:
np.random.seed(42)
arr = np.random.randint(50,100,[3,2])
arr

array([[88, 78],
       [64, 92],
       [57, 70]])

```
아래 셀의 코드 작성
```

In [47]:
arr[:, [0,1]] = arr[:, [1,0]]
arr

array([[78, 88],
       [92, 64],
       [70, 57]])

## 4.다음의 배열에서 각행의 평균을 구하시오.

In [48]:
np.random.seed(42)
arr = np.random.randint(50, 101, (4, 3))
arr

array([[88, 78, 64],
       [92, 57, 70],
       [88, 68, 72],
       [60, 60, 73]])

```
아래 셀의 코드 작성
```

In [51]:
arr.mean(axis=1)

array([76.66666667, 73.        , 76.        , 64.33333333])

## 데이터 설명
- 다음은 2021년 삼성주식 데이터이다
- 시계열 학습이 가능한 형태로 변환되어있다.
- 행마다 10일치의 시작가 ,상한가 , 하한가, 종가 에 대한 행렬이 들어가 있다.

In [52]:
DATA_PATH = "data/"

In [53]:
samsung_stock_3d = np.load(f"{DATA_PATH}samsung_stock_2021_3d.npy")
samsung_stock_3d.shape

(234, 10, 4)

- 한행을 보면 2차원 행렬 형태로 되어있다.
    - 행은 일자
    - 열은 시작가,상한가,하한가,종가 순

In [54]:
samsung_stock_3d[0]

array([[81000, 84400, 80200, 83000],
       [81600, 83900, 81600, 83900],
       [83300, 84500, 82100, 82200],
       [82800, 84200, 82700, 82900],
       [83300, 90000, 83000, 88800],
       [90000, 96800, 89500, 91000],
       [90300, 91400, 87800, 90600],
       [89800, 91200, 89100, 89700],
       [88700, 90000, 88700, 89700],
       [89800, 91800, 88000, 88000]])

## 머신러닝 모델에서 학습이 가능하게 2차원 형태로 변경해보자..


## 5. samsung_stock_3d 변수의 3차원 데이터에 각 행의 행렬을 벡터 형태로 변환하여 데이터셋을 2차원형태로 변경하여 samsung_stock_2d 라는 변수에 담으세요.
- samsung_stock_2d 의 shape -> (234,40)

```
아래 셀의 코드 작성
```

In [62]:
samsung_stock_2d = np.reshape(samsung_stock_3d, (234,40))
samsung_stock_2d

array([[81000, 84400, 80200, ..., 91800, 88000, 88000],
       [81600, 83900, 81600, ..., 87300, 84100, 85000],
       [83300, 84500, 82100, ..., 88000, 83600, 87000],
       ...,
       [78300, 78600, 77100, ..., 78300, 77500, 78100],
       [77400, 78200, 77000, ..., 79400, 78800, 79400],
       [77400, 77600, 76800, ..., 80000, 79300, 79900]])

## 6. samsung_stock_3d 변수의 3차원 데이터에 각 행의 시작가 ,상한가 , 하한가, 종가별로 평균을 구해 2차원 형태로 변경하여 samsung_stock_avg 라는 변수에 담으세요.
- samsung_stock_avg 의 shape -> (234,4)

```
아래 셀의 코드 작성
```

In [63]:
samsung_stock_avg = samsung_stock_3d.mean(axis=1)
samsung_stock_avg

array([[86060., 88820., 85270., 86980.],
       [86620., 89110., 85660., 87180.],
       [86910., 89520., 85860., 87490.],
       [87480., 89970., 86300., 87990.],
       [87950., 90410., 86680., 88510.],
       [88520., 90380., 87060., 88310.],
       [88220., 89690., 86740., 88150.],
       [88070., 89470., 86610., 87760.],
       [87750., 89120., 86260., 87350.],
       [87200., 88680., 85710., 86750.],
       [86670., 88000., 85110., 86150.],
       [86180., 87610., 84800., 85950.],
       [86140., 87450., 84810., 85690.],
       [85720., 87090., 84500., 85430.],
       [85320., 86610., 84060., 84870.],
       [84730., 86040., 83630., 84540.],
       [84410., 85470., 83300., 83900.],
       [83930., 85030., 82920., 83500.],
       [83530., 84520., 82520., 83100.],
       [83590., 84410., 82530., 83150.],
       [83590., 84510., 82750., 83440.],
       [83810., 84590., 82950., 83460.],
       [83720., 84310., 82790., 83230.],
       [83470., 84050., 82550., 83030.],
       [83500., 

## 7. 5번과 6번에서 생성한 변수들의 데이터를 옆으로 합쳐서 x_train 변수에 넣어주세요.

```
아래 셀의 코드 작성
```

In [60]:
x_train = np.concat([samsung_stock_2d, samsung_stock_avg], axis=1)
x_train.shape

(234, 44)

## 8. x_train변수의 각 특성(열)들에 최대값과 최소값들을 구하시오.

```
아래 셀의 코드 작성
```

In [73]:
max = x_train.max(axis=0)
min = x_train.min(axis=0)

## 9.x_train변수의 각 특성(열)들에 분위수기준으로 5% 지점값들과 95% 지점값들을 구하시오

```
아래 셀의 코드 작성
```

In [75]:
x_train_5, x_train_95 = np.quantile(x_train, [0.05, 0.95], axis=0)
print(x_train_5)
print(x_train_95)

[70300.  70965.  70000.  70200.  70300.  70965.  70000.  70200.  70300.
 70965.  70000.  70200.  70300.  70965.  70000.  70200.  70300.  70965.
 70000.  70200.  70300.  70965.  70000.  70200.  70300.  70965.  70000.
 70200.  70300.  70965.  70000.  70200.  70300.  70965.  70000.  70200.
 70300.  70965.  70000.  70200.  70666.5 71169.5 70043.  70430. ]
[86340.  87805.  85205.  86245.  86340.  87805.  85205.  86245.  86340.
 87805.  85205.  86245.  86340.  87805.  85205.  86245.  86340.  87805.
 85205.  86245.  86340.  87440.  85205.  85740.  86135.  86715.  84905.
 85600.  85905.  86270.  84410.  85470.  85735.  86200.  84135.  85335.
 85310.  86070.  84100.  85105.  86088.  87506.  84803.5 85781. ]


## 10. 이상치를 제거해보기
- x_train변수의 특성(열)들에 분위수 기준 5% 지점의 미만값들을 5% 지점값으로 변경하고
- 95% 지점을 초과하는 값들을 95% 지점값으로 변경해보세요.

```
아래 셀의 코드 작성
```

In [78]:
np.clip(x_train, x_train_5, x_train_95)
x_train

array([[81000., 84400., 80200., ..., 88820., 85270., 86980.],
       [81600., 83900., 81600., ..., 89110., 85660., 87180.],
       [83300., 84500., 82100., ..., 89520., 85860., 87490.],
       ...,
       [78300., 78600., 77100., ..., 78010., 76840., 77490.],
       [77400., 78200., 77000., ..., 78090., 77010., 77690.],
       [77400., 77600., 76800., ..., 78270., 77240., 77860.]])

## 11.x_train 데이터셋에서 20%의 데이터의 인덱스들을 리스트에 담아 5번 랜덤하게 반환하는 제너레이터(리스트 형태로 반환 가능) 함수를 만들어주세요
- 단, 5번 랜덤하게 반환하는 과정에서 동일한 행의 인덱스가 나오면 안된다.
    - 한번 나온 행의 인덱스는 다시 나오면 안된다는 의미
    - 모든 행의 인덱스가 한번씩은 무조건 나와야한다.
- 234행 나누기 5를 할경우 나머지가 생기기 때문에 5번째 나오는 인덱스들이 담긴 리스트는 앞서 나온 크기와 차이가 나도 된다.  
- 제너레이터가 어려우신 분들은 그냥 인덱스들을 담고 있는 리스트들을 새로운 리스트에 담아서 return 하셔도 됩니다.

```
아래 셀의 코드 작성하여 함수 구현
```

In [103]:
# 20퍼센트의 인덱스 무작위로 추출해 dataset에 담기
index = np.random.choice(len(x_train)+1, int(len(x_train)*0.2), replace=False)
len(x_train)

234

In [124]:
def split_dataset(dataset):
    total_idx = np.arange(len(dataset))
    slice_20 = int(len(dataset) * 0.2)
    idx_list = []

    for i in range(5):
        # 차집합 이용해서 뽑힌 인덱스 제외하고 unchosen에 저장
        # unchosen = np.setdiff1d(total_idx, np.concatenate(idx_list)) : 비어있는 리스트 안합쳐져서 조건 추가
        if idx_list:
            unchosen = np.setdiff1d(total_idx, np.concatenate(idx_list))
        else:
            unchosen = total_idx

        # 마지막 인덱스일 경우 그냥 전부를 랜덤 돌리기
        if i == 4:
            idx_list.append(np.random.choice(unchosen, len(unchosen), replace = False))
        else:
            idx_list.append(np.random.choice(unchosen, slice_20, replace=False))

    return idx_list

print(split_dataset(x_train))

[array([141, 129,  92,  19,  78, 119, 187, 116,  54,  85,  42, 159,   9,
       156,  35,  34,  87,  37,  23, 183, 216, 230, 162,   3, 120,  73,
        83, 169,   5,  93,  58,  41, 185,  99, 227, 115,  33, 218, 128,
       138,  32,  13, 144, 224, 101, 226]), array([100, 148, 164, 184, 137, 131, 168,  60, 212, 105, 222, 104, 188,
        96,   2, 157, 122, 160, 123,  86,  88,  53, 127,  30, 113, 186,
       195,  95, 199, 179, 181, 190, 231, 114, 130,  61,  82,  64, 180,
         4,  38, 207, 213, 121,  24,  67]), array([182, 134,  10, 126, 165, 149, 135,  43, 112, 204, 202,  90,  63,
       223, 171,  66, 146, 153, 166, 200, 214,  57, 124,  55,  94,  17,
         0,  79, 194, 140,  39, 133,  50,   6, 151, 150, 143, 161,  75,
        65, 219,  45, 233, 145, 132, 201]), array([178, 177, 221,  11,  48,  59,  89, 102, 196,  14, 142,  72,   1,
       175,  47,  77, 228, 106, 197, 217, 176,  16, 136,  44, 229,  36,
        49, 215, 189, 225,  69,  52,  84, 174,  70, 173, 139, 109, 118,
   

- 다음 셀은 위에 함수 실행 결과를 검증하는 부분

In [125]:
index_list = split_dataset(x_train)
lst = []
for idx in index_list:
    lst.extend(idx)
np.all( np.array(sorted(lst)) == np.arange(len(x_train)) ) # True 가 나와야 성공!!

np.True_

## 12.시계열 학습데이터 만들기
- 다음의 데이터는 2021년도 삼성 주식 데이터이다.
- 열부분은 시작가 ,상한가 , 하한가, 종가 순으로 되어있다.
- 행은 2021년도 거래 일자이다.

In [126]:
samsung_stock = np.load(f"{DATA_PATH}samsung_stock_2021.npy")
samsung_stock.shape

(248, 4)

In [11]:
samsung_stock[-5:] # 뒤에 5행만 확인해보자

array([[80200, 80800, 80200, 80500],
       [80600, 80600, 79800, 80200],
       [80200, 80400, 79700, 80300],
       [80200, 80200, 78500, 78800],
       [78900, 79500, 78100, 78300]])

### 시계열 학습데이터 형태로 반환하는 함수를 만드시오.
- samsung_stock 변수의 데이터는 2차원 데이터이다.
- 학습데이터는 행별로 10일치의 행과 4열(시작가 ,상한가 , 하한가, 종가) 형태의 행렬을 담고 있는 3차원 형태의 데이터셋으로 변경하시오.
- 정답데이터는 미래의 5일치의 종가를 예측해야 한다는 가정하에 행별로 미래의 5일치의 종가가 담긴 2차원 형태의 데이터셋으로 변경하시오.
- 1일씩 이동하면서 데이터셋을 구성하시오.

```
아래 셀의 코드 작성하여 함수 구현
```

In [141]:
# def transform_data(samsung_stock,seq_len=10,pred_len=5):
#     

array([[81000, 84400, 80200, 83000],
       [81600, 83900, 81600, 83900],
       [83300, 84500, 82100, 82200],
       [82800, 84200, 82700, 82900],
       [83300, 90000, 83000, 88800],
       [90000, 96800, 89500, 91000],
       [90300, 91400, 87800, 90600],
       [89800, 91200, 89100, 89700],
       [88700, 90000, 88700, 89700],
       [89800, 91800, 88000, 88000],
       [86600, 87300, 84100, 85000],
       [84500, 88000, 83600, 87000],
       [89000, 89000, 86500, 87200],
       [87500, 88600, 86500, 88100],
       [89000, 89700, 86800, 86800],
       [87000, 89900, 86300, 89400],
       [88800, 89200, 86500, 86700],
       [86600, 87700, 85600, 85600],
       [83200, 85600, 83200, 83700],
       [84500, 85000, 82000, 82000],
       [81700, 83400, 81000, 83000],
       [84100, 86400, 83700, 84400],
       [84800, 85400, 83400, 84600],
       [83500, 83800, 82100, 82500],
       [83100, 84000, 82500, 83500],
       [83800, 84200, 83000, 83000],
       [84000, 84800, 82700, 82700],
 

In [ ]:
samsung_stock_2d = np.reshape(samsung_stock_3d, (234,40))

- 다음 셀들은 위에 함수 실행 결과를 검증하는 부분

In [ ]:
x_train , y_train = transform_data(samsung_stock)
x_train.shape, y_train.shape # ((234, 10, 4), (234, 5))

In [ ]:
x_samsung_stock = np.load(f"{DATA_PATH}samsung_stock_2021_3d.npy")
y_samsung_stock = np.load(f"{DATA_PATH}y_train.npy")
np.all(x_samsung_stock == x_train) , np.all(y_samsung_stock == y_train) # 둘다 True 가 나와야 성공!!